name: Base env test

on: [push, pull_request]


jobs:
  test_env_change:
    runs-on: ubuntu-latest
    uses: dorny/paths-filter@v2
    id: file-changes
    with:
      filters: |
        env:
          - environment.yml
  build:
    if: steps.file-changes.outputs.env == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo "source $CONDA/etc/profile.d/conda.sh" >> $HOME/.bash_profile
        conda info

    - name: Install dependencies
      shell: bash -leo pipefail {0}
      run: |
        conda install mamba -n base -c conda-forge
        mamba env create --file environment.yml --name eschool2021
        echo "conda activate eschool2021" >> $HOME/.bash_profile
    - name: Lint with flake8
      shell: bash -leo pipefail {0}
      run: |
        mamba install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests in testing demo project
      shell: bash -leo pipefail {0}
      run: |
        cd testing/fibonacci
        python -m pytest --cov=fibonacci --doctest-modules --doctest-glob='*.rst' -v
        cd ../slides/examples
        python -m pytest -k 'not naive' -v

    - name: Test packaging demo packages
      shell: bash -leo pipefail {0}
      run: |
        python -m build packaging/eschool21_demo
        python -m build packaging/eschool21_cython_demo
        conda build packaging/eschool21_cython_demo/conda-recipe

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: ["windows-latest"]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo "source $CONDA/etc/profile.d/conda.sh" >> $HOME/.bash_profile
          conda info
      - name: Install dependencies
        shell: bash -leo pipefail {0}
        run: |
          conda env create --file environment.yml --name eschool2021
          echo "conda activate eschool2021" >> $HOME/.bash_profile