name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: download and install conda
        run: |
          wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
          chmod u+x Anaconda3-2021.05-Linux-x86_64.sh
          bash Anaconda3-2021.05-Linux-x86_64.sh -b -p $HOME/anaconda3
    - name: init conda
      run: |
       source $HOME/anaconda3/bin/activate
       conda init

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

    - name: Test packaging demo packages
      run: |
        python -m build packaging/eschool21_demo
        python -m build packaging/eschool21_cython_demo
        conda build packaging/eschool21_wheel_demo/conda-recipe

    - name: Build slides
      run: |
        pip install https://github.com/maxnoe/texlive-batch-installation/archive/refs/tags/v0.3.0.tar.gz
        install_texlive -p $HOME/texlive -t 2021 --collections="-a" --package-file packaging/slides/tex-packages.txt --update
        export PATH="$HOME/texlive/2021/bin/x86_64-linux:$PATH"
        make -C packaging/slides
